/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Amenity { 'name' : string, 'count' : bigint }
export interface HouseLayout {
  'id' : bigint,
  'created' : Time,
  'owner' : Principal,
  'floors' : bigint,
  'name' : string,
  'plot' : PlotDimensions,
  'amenities' : Array<Amenity>,
  'rooms' : Array<Room>,
}
export interface PlotDimensions { 'length' : bigint, 'width' : bigint }
export interface Room { 'name' : string, 'length' : bigint, 'width' : bigint }
export type Time = bigint;
export interface _SERVICE {
  'createLayout' : ActorMethod<
    [string, PlotDimensions, bigint, Array<Room>, Array<Amenity>],
    bigint
  >,
  'deleteLayout' : ActorMethod<[bigint], undefined>,
  'getLayout' : ActorMethod<[bigint], HouseLayout>,
  'getLayoutsByUser' : ActorMethod<[Principal], Array<HouseLayout>>,
  'searchLayoutsByName' : ActorMethod<[string], Array<HouseLayout>>,
  'updateLayout' : ActorMethod<[bigint, HouseLayout], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];