/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlotDimensions = IDL.Record({
  'length' : IDL.Nat,
  'width' : IDL.Nat,
});
export const Room = IDL.Record({
  'name' : IDL.Text,
  'length' : IDL.Nat,
  'width' : IDL.Nat,
});
export const Amenity = IDL.Record({ 'name' : IDL.Text, 'count' : IDL.Nat });
export const Time = IDL.Int;
export const HouseLayout = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'owner' : IDL.Principal,
  'floors' : IDL.Nat,
  'name' : IDL.Text,
  'plot' : PlotDimensions,
  'amenities' : IDL.Vec(Amenity),
  'rooms' : IDL.Vec(Room),
});

export const idlService = IDL.Service({
  'createLayout' : IDL.Func(
      [IDL.Text, PlotDimensions, IDL.Nat, IDL.Vec(Room), IDL.Vec(Amenity)],
      [IDL.Nat],
      [],
    ),
  'deleteLayout' : IDL.Func([IDL.Nat], [], []),
  'getLayout' : IDL.Func([IDL.Nat], [HouseLayout], ['query']),
  'getLayoutsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(HouseLayout)],
      ['query'],
    ),
  'searchLayoutsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HouseLayout)],
      ['query'],
    ),
  'updateLayout' : IDL.Func([IDL.Nat, HouseLayout], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlotDimensions = IDL.Record({ 'length' : IDL.Nat, 'width' : IDL.Nat });
  const Room = IDL.Record({
    'name' : IDL.Text,
    'length' : IDL.Nat,
    'width' : IDL.Nat,
  });
  const Amenity = IDL.Record({ 'name' : IDL.Text, 'count' : IDL.Nat });
  const Time = IDL.Int;
  const HouseLayout = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'owner' : IDL.Principal,
    'floors' : IDL.Nat,
    'name' : IDL.Text,
    'plot' : PlotDimensions,
    'amenities' : IDL.Vec(Amenity),
    'rooms' : IDL.Vec(Room),
  });
  
  return IDL.Service({
    'createLayout' : IDL.Func(
        [IDL.Text, PlotDimensions, IDL.Nat, IDL.Vec(Room), IDL.Vec(Amenity)],
        [IDL.Nat],
        [],
      ),
    'deleteLayout' : IDL.Func([IDL.Nat], [], []),
    'getLayout' : IDL.Func([IDL.Nat], [HouseLayout], ['query']),
    'getLayoutsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(HouseLayout)],
        ['query'],
      ),
    'searchLayoutsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HouseLayout)],
        ['query'],
      ),
    'updateLayout' : IDL.Func([IDL.Nat, HouseLayout], [], []),
  });
};

export const init = ({ IDL }) => { return []; };